//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1117 with alias "hasError404"
	/// <summary>_HasError404</summary>
	public partial interface IHasError404 : IPublishedContent
	{
		/// <summary>Error 404 Page</summary>
		IPublishedContent Error404 { get; }
	}

	/// <summary>_HasError404</summary>
	[PublishedContentModel("hasError404")]
	public partial class HasError404 : PublishedContentModel, IHasError404
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasError404";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasError404(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasError404, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Error 404 Page
		///</summary>
		[ImplementPropertyType("error404")]
		public IPublishedContent Error404
		{
			get { return GetError404(this); }
		}

		/// <summary>Static getter for Error 404 Page</summary>
		public static IPublishedContent GetError404(IHasError404 that) { return that.GetPropertyValue<IPublishedContent>("error404"); }
	}
}
